export interface SyntheticProduct {
  id: string;
  sku: string;
  name: string;
  brand_name: string;
  category_code: string;
  category_name: string;
  status: "selling";
  sales_status: "ON_SALE";
  selection_status: "SELECTED";
  estimated_retail_price: number;
  wholesale_price: number;
  curation_role: "HERO" | "CORE" | "TRIAL" | "TREND" | "MARGIN";
  ap_codes: ("AP-01" | "AP-02" | "AP-03" | "AP-04" | "AP-05" | "AP-06")[];
  image_url: string;
  is_synthetic: boolean;
}

export const SYNTHETIC_PRODUCT_CATALOG: SyntheticProduct[] = [
  // --- 1. $10 ~ $15 Range (7 SKUs ~15%) ---
  {
    id: "synth-sku-001",
    sku: "SYNTH-SK-001",
    name: "Invisible Hydrocolloid Acne Pimple Master Patch 36 Patches",
    brand_name: "PorePerfect Solutions",
    category_code: "SK_PATCH",
    category_name: "Patch",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 11.0,
    wholesale_price: 5.5,
    curation_role: "MARGIN",
    ap_codes: ["AP-01", "AP-04", "AP-05"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/pimple_patch.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-002",
    sku: "SYNTH-SK-002",
    name: "Micro-Needle Hyaluronic Acid Eye Spot Patch (2 Packs)",
    brand_name: "RadianceFormula",
    category_code: "SK_PATCH",
    category_name: "Patch",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 13.0,
    wholesale_price: 6.5,
    curation_role: "TRIAL",
    ap_codes: ["AP-02", "AP-05", "AP-06"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/eye_patch.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-003",
    sku: "SYNTH-SK-003",
    name: "Overnight Berry Lip Mask 15g",
    brand_name: "AquaGlow Lab",
    category_code: "SK_LIP",
    category_name: "Lip Care",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 14.0,
    wholesale_price: 7.0,
    curation_role: "HERO",
    ap_codes: ["AP-01", "AP-04", "AP-05"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/lip_mask.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-004",
    sku: "SYNTH-SK-004",
    name: "Deep Hydration Gentle Foam Cleanser 120ml",
    brand_name: "AquaGlow Lab",
    category_code: "SK_CLEANSER",
    category_name: "Cleanser",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 14.5,
    wholesale_price: 7.25,
    curation_role: "CORE",
    ap_codes: ["AP-01", "AP-04"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/cleanser_02.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-005",
    sku: "SYNTH-SK-005",
    name: "Aloe Vera Soothing Gel 300ml",
    brand_name: "PhytoCalm Botanicals",
    category_code: "SK_CREAM",
    category_name: "Cream / Moisturizer",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 12.0,
    wholesale_price: 6.0,
    curation_role: "TRIAL",
    ap_codes: ["AP-01", "AP-04"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/aloe_gel.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-006",
    sku: "SYNTH-SK-006",
    name: "Tea Tree Clarifying Sheet Mask (5 Packs)",
    brand_name: "PorePerfect Solutions",
    category_code: "SK_MASK",
    category_name: "Sheet Mask",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 13.5,
    wholesale_price: 6.75,
    curation_role: "CORE",
    ap_codes: ["AP-01", "AP-04", "AP-05"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/teatree_mask.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-007",
    sku: "SYNTH-HR-001",
    name: "Argan Daily Hair Silk Serum 80ml",
    brand_name: "SilkBond Professional",
    category_code: "HR_STYLING",
    category_name: "Styling",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 15.0,
    wholesale_price: 7.5,
    curation_role: "TRIAL",
    ap_codes: ["AP-03"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/hair_oil.jpg",
    is_synthetic: true
  },

  // --- 2. $15 ~ $20 Range (13 SKUs ~25%) ---
  {
    id: "synth-sku-008",
    sku: "SYNTH-SK-008",
    name: "Cica Mild Gentle Gel Cleanser 200ml",
    brand_name: "DermaPure K-Beauty",
    category_code: "SK_CLEANSER",
    category_name: "Cleanser",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 17.5,
    wholesale_price: 8.75,
    curation_role: "CORE",
    ap_codes: ["AP-01", "AP-02", "AP-04"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/cleaner_01.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-009",
    sku: "SYNTH-SK-009",
    name: "Hydrogel Real Deep Collagen Mask (4 Packs)",
    brand_name: "BioSecret K-Skin",
    category_code: "SK_MASK",
    category_name: "Sheet Mask",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 18.5,
    wholesale_price: 9.25,
    curation_role: "HERO",
    ap_codes: ["AP-01", "AP-02", "AP-05"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/mask_collagen.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-010",
    sku: "SYNTH-SK-010",
    name: "Relief Watery Sunscreen Essence SPF50+ 50ml",
    brand_name: "PhytoCalm Botanicals",
    category_code: "SK_SUN",
    category_name: "Sun Care",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 19.5,
    wholesale_price: 9.75,
    curation_role: "HERO",
    ap_codes: ["AP-01", "AP-02", "AP-04"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/sunscreen.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-011",
    sku: "SYNTH-SK-011",
    name: "BHA Clarifying Exfoliating Toner 180ml",
    brand_name: "PorePerfect Solutions",
    category_code: "SK_TONER",
    category_name: "Toner",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 19.0,
    wholesale_price: 9.5,
    curation_role: "CORE",
    ap_codes: ["AP-02", "AP-04"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/toner_02.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-012",
    sku: "SYNTH-SK-012",
    name: "Heartleaf Soothing Calming Toner 250ml",
    brand_name: "PhytoCalm Botanicals",
    category_code: "SK_TONER",
    category_name: "Toner",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 19.5,
    wholesale_price: 9.75,
    curation_role: "HERO",
    ap_codes: ["AP-01", "AP-02", "AP-05"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/toner_01.jpg",
    is_synthetic: true
  },

  // Additional 8 SKUs in $15~$20 range
  ...Array.from({ length: 8 }).map((_, i) => ({
    id: `synth-sku-1520-${i + 1}`,
    sku: `SYNTH-1520-${i + 1}`,
    name: `Daily Essence Lotion Formula ${i + 1} 100ml`,
    brand_name: i % 2 === 0 ? "DermaPure K-Beauty" : "AquaGlow Lab",
    category_code: "SK_CREAM",
    category_name: "Cream / Moisturizer",
    status: "selling" as const,
    sales_status: "ON_SALE" as const,
    selection_status: "SELECTED" as const,
    estimated_retail_price: 16.0 + (i % 4) * 1.0,
    wholesale_price: 8.0 + (i % 4) * 0.5,
    curation_role: "CORE" as const,
    ap_codes: ["AP-01", "AP-02", "AP-04"] as ("AP-01" | "AP-02" | "AP-03" | "AP-04" | "AP-05" | "AP-06")[],
    image_url: `https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/lotion_${i}.jpg`,
    is_synthetic: true
  } as SyntheticProduct)),

  // --- 3. $20 ~ $30 Range (20 SKUs ~40% Core) ---
  {
    id: "synth-sku-021",
    sku: "SYNTH-SK-021",
    name: "Snail Mucin 96 Power Repairing Essence 100ml",
    brand_name: "BioSecret K-Skin",
    category_code: "SK_SERUM",
    category_name: "Serum / Essence",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 24.0,
    wholesale_price: 12.0,
    curation_role: "HERO",
    ap_codes: ["AP-01", "AP-02", "AP-05"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/essence_01.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-022",
    sku: "SYNTH-SK-022",
    name: "Niacinamide 10% + Zinc Brightening Ampoule 30ml",
    brand_name: "RadianceFormula",
    category_code: "SK_SERUM",
    category_name: "Serum / Essence",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 22.0,
    wholesale_price: 11.0,
    curation_role: "MARGIN",
    ap_codes: ["AP-02", "AP-05"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/ampoule_01.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-023",
    sku: "SYNTH-SK-023",
    name: "Centella Asiatica Barrier Relief Ampoule 50ml",
    brand_name: "PhytoCalm Botanicals",
    category_code: "SK_SERUM",
    category_name: "Serum / Essence",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 26.0,
    wholesale_price: 13.0,
    curation_role: "CORE",
    ap_codes: ["AP-01", "AP-02", "AP-04"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/cica_ampoule.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-024",
    sku: "SYNTH-SK-024",
    name: "Ceramide NP Barrier Recovery Cream 80ml",
    brand_name: "DermaPure K-Beauty",
    category_code: "SK_CREAM",
    category_name: "Cream / Moisturizer",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 25.0,
    wholesale_price: 12.5,
    curation_role: "CORE",
    ap_codes: ["AP-01", "AP-02", "AP-04"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/cream_ceramide.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-025",
    sku: "SYNTH-SK-025",
    name: "Water Bank Hydro Gel Cream 50ml",
    brand_name: "AquaGlow Lab",
    category_code: "SK_CREAM",
    category_name: "Cream / Moisturizer",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 23.0,
    wholesale_price: 11.5,
    curation_role: "TRIAL",
    ap_codes: ["AP-01", "AP-04"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/cream_waterbank.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-026",
    sku: "SYNTH-HR-002",
    name: "Anti-Hair Loss Root Strengthening Shampoo 500ml",
    brand_name: "K-Scalp Lab",
    category_code: "HR_SHAMPOO",
    category_name: "Hair Care",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 26.0,
    wholesale_price: 13.0,
    curation_role: "HERO",
    ap_codes: ["AP-01", "AP-03"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/shampoo_scalp.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-027",
    sku: "SYNTH-HR-003",
    name: "Miracle 7-Second Protein Hair Treatment Mask 200ml",
    brand_name: "SilkBond Professional",
    category_code: "HR_TREATMENT",
    category_name: "Hair Treatment",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 24.5,
    wholesale_price: 12.25,
    curation_role: "HERO",
    ap_codes: ["AP-03"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/hair_treatment.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-028",
    sku: "SYNTH-HR-004",
    name: "Scalp Cooling Scaling Tonic 120ml",
    brand_name: "K-Scalp Lab",
    category_code: "HR_SCALP",
    category_name: "Scalp Care",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 21.0,
    wholesale_price: 10.5,
    curation_role: "CORE",
    ap_codes: ["AP-03"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/scalp_tonic.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-029",
    sku: "SYNTH-BD-001",
    name: "Body Acne Clarifying AHA Spray 150ml",
    brand_name: "PorePerfect Solutions",
    category_code: "BD_PERSONAL",
    category_name: "Body Care",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 21.5,
    wholesale_price: 10.75,
    curation_role: "CORE",
    ap_codes: ["AP-01", "AP-04"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/body_spray.jpg",
    is_synthetic: true
  },

  // Additional 11 SKUs in $20~$30 range
  ...Array.from({ length: 11 }).map((_, i) => ({
    id: `synth-sku-2030-${i + 1}`,
    sku: `SYNTH-2030-${i + 1}`,
    name: `Advanced Active Serum Formula No.${i + 1} 50ml`,
    brand_name: i % 2 === 0 ? "BioSecret K-Skin" : "PhytoCalm Botanicals",
    category_code: i % 3 === 0 ? "SK_SERUM" : i % 3 === 1 ? "SK_CREAM" : "HR_SHAMPOO",
    category_name: "Serum / Skincare",
    status: "selling" as const,
    sales_status: "ON_SALE" as const,
    selection_status: "SELECTED" as const,
    estimated_retail_price: 23.0 + (i % 6) * 1.0,
    wholesale_price: 11.5 + (i % 6) * 0.5,
    curation_role: (i % 2 === 0 ? "HERO" : "CORE") as "HERO" | "CORE",
    ap_codes: (i % 3 === 2 ? ["AP-03"] : ["AP-01", "AP-02", "AP-05"]) as ("AP-01" | "AP-02" | "AP-03" | "AP-04" | "AP-05" | "AP-06")[],
    image_url: `https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/serum_${i}.jpg`,
    is_synthetic: true
  } as SyntheticProduct)),

  // --- 4. $30 ~ $40 Range (7 SKUs ~15%) ---
  {
    id: "synth-sku-041",
    sku: "SYNTH-TL-001",
    name: "Microcurrent Face Lifting Gua Sha Tool",
    brand_name: "BioSecret K-Skin",
    category_code: "TL_DEVICE",
    category_name: "Beauty Tool",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 34.0,
    wholesale_price: 17.0,
    curation_role: "TREND",
    ap_codes: ["AP-05", "AP-06"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/guasha_tool.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-042",
    sku: "SYNTH-SK-042",
    name: "Pro-Collagen Intensive Night Cream 50ml",
    brand_name: "LuxuryCell Stem",
    category_code: "SK_CREAM",
    category_name: "Cream / Moisturizer",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 35.0,
    wholesale_price: 17.5,
    curation_role: "TREND",
    ap_codes: ["AP-06"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/cream_collagen.jpg",
    is_synthetic: true
  },
  ...Array.from({ length: 5 }).map((_, i) => ({
    id: `synth-sku-3040-${i + 1}`,
    sku: `SYNTH-3040-${i + 1}`,
    name: `Premium Derm Treatment Set ${i + 1}`,
    brand_name: "LuxuryCell Stem",
    category_code: "SK_SERUM",
    category_name: "Serum / Essence",
    status: "selling" as const,
    sales_status: "ON_SALE" as const,
    selection_status: "SELECTED" as const,
    estimated_retail_price: 32.0 + i * 1.5,
    wholesale_price: 16.0 + i * 0.75,
    curation_role: "TREND" as const,
    ap_codes: ["AP-06"] as ("AP-01" | "AP-02" | "AP-03" | "AP-04" | "AP-05" | "AP-06")[],
    image_url: `https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/prem_${i}.jpg`,
    is_synthetic: true
  } as SyntheticProduct)),

  // --- 5. $40 ~ $50 Range (3 SKUs ~5%) ---
  {
    id: "synth-sku-048",
    sku: "SYNTH-SK-048",
    name: "PDRN Salmon DNA Youth Ampoule 50ml",
    brand_name: "LuxuryCell Stem",
    category_code: "SK_SERUM",
    category_name: "Serum / Essence",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 44.0,
    wholesale_price: 22.0,
    curation_role: "HERO",
    ap_codes: ["AP-06"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/pdrn.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-049",
    sku: "SYNTH-SK-049",
    name: "Peptide Anti-Aging Youth Repair Cream 50ml",
    brand_name: "LuxuryCell Stem",
    category_code: "SK_CREAM",
    category_name: "Cream / Moisturizer",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 46.0,
    wholesale_price: 23.0,
    curation_role: "TREND",
    ap_codes: ["AP-06"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/cream_peptide.jpg",
    is_synthetic: true
  },
  {
    id: "synth-sku-050",
    sku: "SYNTH-SK-050",
    name: "Ultimate Gold EGF Cell Serum 50ml",
    brand_name: "LuxuryCell Stem",
    category_code: "SK_SERUM",
    category_name: "Serum / Essence",
    status: "selling",
    sales_status: "ON_SALE",
    selection_status: "SELECTED",
    estimated_retail_price: 48.0,
    wholesale_price: 24.0,
    curation_role: "HERO",
    ap_codes: ["AP-06"],
    image_url: "https://shzfrppdobpmrstcjfqu.supabase.co/storage/v1/object/public/company-uploads/synthetic/egf_serum.jpg",
    is_synthetic: true
  }
];

export function getSyntheticProductsForAp(apCode: string): SyntheticProduct[] {
  return SYNTHETIC_PRODUCT_CATALOG.filter(p => p.ap_codes.includes(apCode as any));
}
